name: Extract GitHub Audit Logs

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  extract-audit-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch audit logs
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/orgs/YOUR_ORG_NAME/audit-log > audit-log.json

    - name: Upload to Server
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no audit-log.json user@your-server:/path/to/destination/   # Password to be added to Secrets

    - name: Clean up
      run: rm audit-log.json
