name: Extract GitHub Audit Logs

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  extract-audit-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch audit logs
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/orgs/YOUR_ORG_NAME/audit-log > audit-log.json

    - name: Upload audit log as artifact
      uses: actions/upload-artifact@v2
      with:
        name: audit-log
        path: audit-log.json

    - name: Send email with audit log
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.your-email-provider.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: GitHub Audit Logs
        body: Please find the attached audit log.
        to: recipient@example.com
        from: sender@example.com
        attachments: audit-log.json

    - name: Clean up
      run: rm audit-log.json
