name: Extract GitHub Audit Logs - 5

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  extract-audit-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch audit logs
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/json" \
             -H "Accept-Encoding: gzip, deflate, br, zstd" \
             -H "Accept-Language: en-GB,en-US;q=0.9,en;q=0.8" \
             -H "Connection: keep-alive" \
            -data; boundary=----WebKitFormBoundaryUfHoXG0cLjhlFsFQ" \
             -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" \
             -H "X-Requested-With: XMLHttpRequest" \
             https://github.com/orgs/sl-githubtraining/audit-log/export.json > audit-log.json

    - name: Upload audit log as artifact
      uses: actions/upload-artifact@v4
      with:
        name: audit-log
        path: audit-log.json

    - name: Send email with audit log
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: GitHub Audit Logs
        body: Please find the attached audit log.
        to: sulaiman.lodewyk@absa.africa
        from: slodewyk@gmail.com
        attachments: audit-log.json

    - name: Clean up
      run: rm audit-log.json
